### ISSUE TITLE
IPS Logs

### ISSUE THREAD

**Issue by ndbnimbus** [stylemessiah/Unifi-Auto-Ban#3]
It cant find any IPS Logs.

But it seems to run.  It should pick up at least 1 person, and unblock 2 from last week that are in there.. but it's not getting any IPS logs.

---
Loading currently banned MAC addresses:

Banned MAC's read from: /var/www/html/autoban/bannedmacs_aa4nuuj7.log

Currently banned MAC addresses found in banned mac log file: 0

IPS log found for site: No

**Comment by stylemessiah** [comment]
I dont think IPS logs last that long from memory.....

Really going to bed now, more later, afer sleep

**Comment by ndbnimbus** [comment]
Working! 

Thanks for the tips.  My missing step was the curl module and mis-named the site address in one of the php files.. so all my fault!
